name: "cloudflared"
description: "cloudflare tunnel client"
version: "1.0.0"
slug: "cloudflare_tunnel"
url: "https://github.com/shadow578/ha-playit-addon/tree/main/cloudflared"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
options:
  token: null
schema:
  token: str
