name: "Playit"
description: "Playit.gg agent"
version: "1.0.0"
slug: "playit_gg"
url: "https://github.com/shadow578/ha-playit-addon/tree/main/playit"
init: false
arch:
  - aarch64
  - amd64
  - armv7
