name: "playit-agent"
description: "Playit.gg agent"
version: "1.0.0"
slug: "playit_agent"
url: "https://github.com/shadow578/ha-tunneling-addons/tree/main/playit-agent"
init: false
arch:
  - aarch64
  - amd64
  - armv7
